#!/usr/bin/env bash
# Generate and install udev rules that give the FCB camera stable device names.
#
#   fcb_udev_setup.sh            # detect, print the rules, install with sudo
#   fcb_udev_setup.sh --dry-run  # detect and print only
#
# Plug the camera in first. The video node is found by its V4L2 card name; the
# VISCA port by probing every /dev/ttyACM* and /dev/ttyUSB* with a zoom
# inquiry (the same test the driver uses), then reading its USB IDs.
set -euo pipefail
DRY=0; [[ "${1:-}" == "--dry-run" ]] && DRY=1
HINTS="${FCB_NAME_HINTS:-neohd fcb harrier}"

video=""
for node in /dev/video*; do
  name=$(cat "/sys/class/video4linux/$(basename "$node")/name" 2>/dev/null | tr 'A-Z' 'a-z' || true)
  idx=$(cat "/sys/class/video4linux/$(basename "$node")/index" 2>/dev/null || echo 0)
  for h in $HINTS; do
    if [[ "$name" == *"$h"* && "$idx" == "0" ]]; then video="$node"; fi
  done
done
if [[ -n "$video" ]]; then
  echo "video node: $video ($(cat /sys/class/video4linux/$(basename "$video")/name))"
else
  echo "warning: no /dev/video* card name matched '$HINTS' -- is the camera plugged in?" >&2
fi

visca=""
for port in /dev/ttyACM* /dev/ttyUSB*; do
  [[ -e "$port" ]] || continue
  if python3 - "$port" <<'PY'
import sys, serial, time
port = sys.argv[1]
for baud in (9600, 38400, 115200):
    try:
        with serial.Serial(port, baud, timeout=0.3) as s:
            s.reset_input_buffer()
            ok = 0
            for _ in range(2):
                s.write(bytes([0x81, 0x09, 0x04, 0x47, 0xFF]))
                r = s.read(16)
                if len(r) >= 7 and r[0] == 0x90 and r[1] == 0x50 and all(b <= 0x0F for b in r[2:6]):
                    ok += 1
            if ok == 2:
                print(baud)
                sys.exit(0)
    except Exception:
        pass
sys.exit(1)
PY
  then visca="$port"; break; fi
done

rules="$(mktemp)"
cat > "$rules" <<'HDR'
# Generated by fcb_udev_setup.sh -- stable names for the Sony FCB-EV9520L.
SUBSYSTEM=="video4linux", ATTR{name}=="*NeoHD*", ATTR{index}=="0", SYMLINK+="fcb_video"
SUBSYSTEM=="video4linux", ATTR{name}=="*FCB*", ATTR{index}=="0", SYMLINK+="fcb_video"
SUBSYSTEM=="video4linux", ATTR{name}=="*Harrier*", ATTR{index}=="0", SYMLINK+="fcb_video"
HDR
if [[ -n "$visca" ]]; then
  vid=$(udevadm info -q property -n "$visca" | sed -n 's/^ID_VENDOR_ID=//p')
  pid=$(udevadm info -q property -n "$visca" | sed -n 's/^ID_MODEL_ID=//p')
  serial=$(udevadm info -q property -n "$visca" | sed -n 's/^ID_SERIAL_SHORT=//p')
  echo "visca port: $visca (usb $vid:$pid serial '${serial:-n/a}')"
  line="SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"$vid\", ATTRS{idProduct}==\"$pid\""
  [[ -n "$serial" ]] && line+=", ATTRS{serial}==\"$serial\""
  line+=", SYMLINK+=\"fcb_visca\", MODE=\"0666\""
  echo "$line" >> "$rules"
  echo "SUBSYSTEM==\"usb\", ATTR{idVendor}==\"$vid\", ATTR{idProduct}==\"$pid\", MODE=\"0664\", GROUP=\"plugdev\"" >> "$rules"
else
  echo "warning: no serial port answered VISCA; rule for /dev/fcb_visca not generated" >&2
fi

echo "---- rules ----"; cat "$rules"; echo "---------------"
if [[ $DRY == 1 ]]; then rm -f "$rules"; exit 0; fi
sudo install -m 0644 "$rules" /etc/udev/rules.d/99-fcb-camera.rules
sudo udevadm control --reload
sudo udevadm trigger
rm -f "$rules"
sleep 1
ls -l /dev/fcb_video /dev/fcb_visca 2>/dev/null || echo "symlinks will appear after replugging the camera"
